### ISSUE TITLE
[BUG] Navbar options are not working

### ISSUE THREAD

**Issue by sundaram-sharma** [amanrajrana/RobustKey-PasswordGenerator#11]
### **Description of the bug**

Navbar options on the Navbar 
Namely: _Home, About and Contact_ 
are not working when clicked

<img width="689" alt="Screenshot 2023-10-05 002546" src="https://github.com/amanrajrana/RobustKey-PasswordGenerator/assets/98935619/73c27c85-bc6d-4aaf-aed4-e026c389481f">

**Why do we need this?**

This will add more information and make the website complete with integrity.

- [x] I am willing to resolve this bug.
- [x] I agree to follow this project's Code of Conduct

**Comment by sundaram-sharma** [comment]
@amanrajrana Can you please assign me to this issue to solve this ?

**Comment by amanrajrana** [comment]
Hey @sundaram-sharma as you know website is host on GitHub page. And in GitHub page React Router not working. But if you have any idea then work on it.

**Comment by amanrajrana** [comment]
@sundaram-sharma assigned to you.

**Comment by saurabhbakolia** [comment]
Hello @amanrajrana , 
I have added the react-router-dom and also I fixed the issue of github-pages. 
please check my PR. and Assign this issue to me 🙂. 
![image](https://github.com/amanrajrana/RobustKey-PasswordGenerator/assets/78996216/9f43b4fb-6a1d-406b-acda-94fbbb6e509a)

![image](https://github.com/amanrajrana/RobustKey-PasswordGenerator/assets/78996216/9c9a22e5-7581-4d34-9e42-7a9a9c94a091)

**Comment by amanrajrana** [comment]
@saurabhbakolia @sundaram-sharma This bug has been fixed in PR #20. Thanks for your interest.
