### ISSUE TITLE
🌟 [Feature] Add contributors section

### ISSUE THREAD

**Issue by amanrajrana** [amanrajrana/RobustKey-PasswordGenerator#14]
**Description:**
Requesting the addition of a contributors section on the website, displaying avatars, names, and other relevant information of contributors, along with links to their GitHub profiles.

API for fetching contributors: [https://api.github.com/repos/amanrajrana/RobustKey-PasswordGenerator/contributors](https://api.github.com/repos/amanrajrana/RobustKey-PasswordGenerator/contributors)

**Comment by ayush-raj13** [comment]
Hello @amanrajrana, can you please assign me this task and label it as hacktoberfest and hacktoberfest-accepted.

**Comment by ayush-raj13** [comment]
Can we use all-contributors bot?

**Comment by ayush-raj13** [comment]
Where should I add the contributors, in the homepage itself or creating a separate page for it that can be accessed through navbar.

I also noticed that react routers is not set up for this project. As a result, navbar is not working.

**Comment by amanrajrana** [comment]
hey @ayush-raj13 create a separate page for the contributors.
React Routers is not set up because the app is hosted on the GitHub Page. If you wish you can setup it

**Comment by amanrajrana** [comment]
Fix in #20
