### ISSUE TITLE
🎨 [Enhancement] Add icon to copy password instead of "Click to copy password" text

### ISSUE THREAD

**Issue by Brij247** [amanrajrana/RobustKey-PasswordGenerator#17]
### Description of Feature

The current "Click to copy password" button is text-only. This can be visually confusing for users, and it can also be difficult to understand for users with disabilities.

![Screenshot 2023-10-05 095136](https://github.com/amanrajrana/RobustKey-PasswordGenerator/assets/72482132/817f4f00-ed6b-4029-9b1e-f0683a664310)

### Proposed Solution

I propose that we add an icon to the end of text box and remove the text. This will make the button more visually appealing and easier to understand for all users.
![image](https://github.com/amanrajrana/RobustKey-PasswordGenerator/assets/72482132/f4573af6-d7a5-48ad-af34-55cca6a88b4d)

### Additional Information

**Suggested Icon:**

A clipboard icon would be a good choice for the icon. It is a universally recognized symbol for copying text.

**Implementation Details:**

The icon could be added to the text box using CSS or by using an SVG image. The text(Click to copy password) could be removed.

**Benefits:**

- The button will be more visually appealing.
- The button will be easier to understand for all users, including users with disabilities.
- The button will be more consistent with other buttons in the application.

**Comment by amanrajrana** [comment]
@Brij247  Impressive ideas 👍.  Apply feature.  But make sure.  The UI looks good even on mobile screens.

**Comment by kunal-511** [comment]
I WANT TO WORK ON THIS PLEASE ASSIGN ME THIS TASK
