### ISSUE TITLE
🔴 [other] code refactoring

### ISSUE THREAD

**Issue by Amitkm-450** [amanrajrana/RobustKey-PasswordGenerator#27]
### Description

Refactor the code by replacing hardcoded instances of CheckBoxWithLabel with an array storing props as objects. Utilize the map function to dynamically generate select tags, enhancing code flexibility and maintainability.

like in the below the same code is repeated many times:
<img width="269" alt="Screenshot 2023-10-06 230450" src="https://github.com/amanrajrana/RobustKey-PasswordGenerator/assets/130365583/27e8e351-004a-41db-9b5d-da06d168abed">

**Comment by Amitkm-450** [comment]
Can you assign this to me ?

**Comment by amanrajrana** [comment]
@Amitkm-450 assigned to you. 
Happy coding

**Comment by amanrajrana** [comment]
Resolve in #28
