### ISSUE TITLE
⭐ [Feature] About Section

### ISSUE THREAD

**Issue by shrutiiigupta** [amanrajrana/RobustKey-PasswordGenerator#32]
### Description of Feature

As of Now, there is no about section

### Proposed Solution (if applicable)

I can create a about section for this app.

**Comment by amanrajrana** [comment]
@shrutiiigupta Are you interested in working on it?

**Comment by shrutiiigupta** [comment]
Yes, I am interested.
Pls, Provide me the content to be added in about section.
