### ISSUE TITLE
⭐ [Feature] Make a navbar with hamburger icon for mobile view

### ISSUE THREAD

**Issue by akash0708** [amanrajrana/RobustKey-PasswordGenerator#38]
### Description of Feature

There is no dedicated navbar for mobile view. 

### Proposed Solution (if applicable)

A navbar with a hamburger menu to open it.

**Comment by amanrajrana** [comment]
@akash0708 Are you interested in working on it?

**Comment by Shashankpantiitbhilai** [comment]
I am interested ,please assign this to me

**Comment by akash0708** [comment]
@amanrajrana yes, I would love to.

**Comment by Albert-2** [comment]
hey...
I'll be more than happy to contribute, please assign me this issue
THANK YOU...!!

**Comment by akash0708** [comment]
@amanrajrana , should I start working on it? Can you please assign it and add the hacktober fest accepted label?

**Comment by amanrajrana** [comment]
@akash0708, @Shashankpantiitbhilai, @saurabhbakolia and @Albert-2 

Anyone interested in working on this issue, please go ahead and open a PR with a screenshot or screen recording of your solution. I'll merge it once it's ready. 
Thanks!

**Comment by saurabhbakolia** [comment]
Yes, I would love to contribute.

**Comment by Shashankpantiitbhilai** [comment]
I am interested to work on the same issue

**Comment by amanrajrana** [comment]
Implement in #39
