### ISSUE TITLE
🔴 [UI Improvement] Alignment is not correct 

### ISSUE THREAD

**Issue by GautamTirumala** [amanrajrana/RobustKey-PasswordGenerator#40]
### Description

I Think the alignment of the component is not correct and it's gives a bad UX. If you want to improve it assign it to me I would love to contribute to this.

![Screenshot 2023-10-11 175348](https://github.com/amanrajrana/RobustKey-PasswordGenerator/assets/71633661/8602dac9-cc9d-4f60-8847-1a4e90e17131)

**Comment by amanrajrana** [comment]
@GautamTirumala Go for it. Assigning to you

**Comment by GautamTirumala** [comment]
Also I have noticed that the checkbox is not aligned properly on mid screen sizes. I am also fixing it 🤝


![Screenshot 2023-10-11 215022](https://github.com/amanrajrana/RobustKey-PasswordGenerator/assets/71633661/7c095027-6395-493f-bb14-d4b8af6b97b2)

**Comment by GautamTirumala** [comment]
@amanrajrana  Close this issue as it is already merged.
