### ISSUE TITLE
🔴 [BUG] Hovering effect is not so effective and active page can't be recognised easily

### ISSUE THREAD

**Issue by Nincompup** [amanrajrana/RobustKey-PasswordGenerator#43]
### Description of the bug

The hovering effect on the navbar link is not so efficient and the user can't get easily which page is currently active.

### Please add screenshots (if applicable)

https://github.com/amanrajrana/RobustKey-PasswordGenerator/assets/114563503/8c584768-e942-4278-8853-62a6fa2b3c08

**Comment by Nincompup** [comment]
Hey @amanrajrana could you assign this issue to me? So I can fix this bug.

**Comment by amanrajrana** [comment]
@Nincompup assigned to you.

Happy coding

**Comment by amoghpujari** [comment]
Hii @amanrajrana can I contribute to this issue?

**Comment by amanrajrana** [comment]
@amoghpujari Yes, Go ahead

**Comment by amanrajrana** [comment]
The issue is not Resolved.

**Comment by hmadhsan** [comment]
Hi, Aman can you assign this issue to me if it is still not resolved?

**Comment by amanrajrana** [comment]
Fixed in #63
