### ISSUE TITLE
⭐ [Feature] Add GitHub repo link to the website navbar

### ISSUE THREAD

**Issue by amanrajrana** [amanrajrana/RobustKey-PasswordGenerator#46]
### Description of Feature

Add this GitHub repo link to the website navbar so anyone can visit this GitHub repo from the website.

### Proposed Solution (if applicable)

Shift `nav links` to the centre and place the GitHub icon behind the dark mode toggle button.

![Screenshot 2023-10-12 190921](https://github.com/amanrajrana/RobustKey-PasswordGenerator/assets/75106349/44a4ac3b-c9f4-46a7-a56a-0c5b7540acd8)

**Note:**
 Don't add any icon library for the icon. you can use only `SVG` icon.

**Comment by VaibhavKambar7** [comment]
hey , can i work on this?

**Comment by amanrajrana** [comment]
@VaibhavKambar7 Yes
