### ISSUE TITLE
📃 [Feature] Request for Adding CONTRIBUTING.md

### ISSUE THREAD

**Issue by amanrajrana** [amanrajrana/RobustKey-PasswordGenerator#53]
### Description of Feature

Hi there! I've assigned this issue to request the addition of a `CONTRIBUTING.md` file. This file will serve as a valuable resource for contributors and should include:

### Proposed Solution (if applicable)

Certainly, here's a concise description of what the `CONTRIBUTING.md` file should contain:

1. **Guidelines:** Clear guidelines on how to contribute to our project.

2. **Pull Request Process:** Steps to follow when creating pull requests, including code review and testing.

3. **Coding Standards:** Any coding style or standards that contributors should adhere to.

4. **Issue Reporting:** Information on how to report bugs, suggest enhancements, or open issues.

This `CONTRIBUTING.md` file will help streamline contributions and improve collaboration. Thank you for your help with this!

**Comment by saurabhbakolia** [comment]
Hey, @amanrajrana  I would like to work on it.

**Comment by amanrajrana** [comment]
@saurabhbakolia Okay. Go ahead

**Comment by saurabhbakolia** [comment]
Hello @amanrajrana  I have added contributing.md file, 
let me know if you want any other changes. 

And please make it hackoctoberfest accepted🙂

**Comment by amanrajrana** [comment]
Added in #62

**Comment by saurabhbakolia** [comment]
Hey, I think here you should add, hackoctober fest accepted, I am not able to see it in my submitted PR. Can you please add the labels.

**Comment by amanrajrana** [comment]
@saurabhbakolia keep patience.... It takes some time to appear in hacktoberfest profile.
