### ISSUE TITLE
⭐ [Feature] Password Strength Indicator 

### ISSUE THREAD

**Issue by bj-jiwrajka** [amanrajrana/RobustKey-PasswordGenerator#66]
### Description of Feature

**Feature Overview:**
I propose adding a password strength indicator feature to our React project. This feature will help users create stronger and more secure passwords by providing real-time feedback on the strength of the passwords they generate.

**Use Case:**
The password strength indicator will be especially useful when users are creating or changing their passwords for various online accounts, ensuring that they meet security requirements and best practices.

**User Impact:**
Implementing this feature will have a direct impact on the security of our users. It will empower them to make informed decisions when creating passwords, resulting in a safer online experience.

### Proposed Solution
**Functional Description:**
The password strength indicator will assess several criteria to determine the strength of a password. It should include checks for:

    Password length (minimum 8 characters).
    Character diversity (uppercase, lowercase, numbers, and special characters).
    The absence of common patterns and easily guessable phrases.

**Technical Details:**
Regular expressions and weighting criteria can be used to evaluate password strength. For instance, we can assign points for each criterion and display a cumulative score. The indicator should update as the user types.

_No response_

**Comment by bj-jiwrajka** [comment]
@amanrajrana please assign this to me

**Comment by amanrajrana** [comment]
@bj-jiwrajka Assigned to you

Happy Hacking :)
